### ISSUE TITLE
Ideas: Do not make class. Static typed. Variables by default is constants.

### ISSUE THREAD

**Issue by isergey** [kram/kram#39]
* Instead class, make interface and implementations. 
* All methods returns self object by default if not return anything.
* Make static typed language with reference counting garbage collector.
* Make variables constats by default.
* Make primitive types with unsigned analogs: string (unicode string), (u)byte, (u)short, (u)int, (u)int64, (u)float, (u)float64, null.
* Do not make exceptions for error. 
* If method can return null, make return type Nullable[T].
* Make named arguments.
* Make function as objects.
* Don't make static method. Make modules.
* Make annotations (see python annotations).

```
interface Animal {
  string getName(); // method return string
  goToSleep(uint hours, uint minutes, wakeUpCallback=(string wakeUpMessage)); // method return self object

}

interface Dog extends Animal{
  addChild(Dog child);
  Nullable<Dog> getFirstChild(); // return child or null if  
}

// implementation of Dog interface. Implementation can't exist witout interface. Have same name.
impl Dog {
  private mut uint sleepMinutes = 0; // "mut" make variable mutable
  prvate mut string name;
  private List<Dog> children;

 // Constructor
 Dog(string name) { 
    this.name = name;
  }
  string getName() {
     return this.name;
  }
  
  goToSleep(uint hours=8, unit minutes = 0, wakeUpCallback=null) { // with default args
    this.sleepHours = hours * 60 + minutes;
    // sleeping
    if (wakeUpCallback) {
      wakeUpCallback("Im waking up!");
   }
  }

  addChild(Dog child) {
     this.children.add(child);
  }
}
string name = IO.Console.readLine();
Dog dog = new Dog(name);
IO.Console.writeLine('Dogs name is ${dog.getName()}'); template strings

dog.addChild(new Dog("Spark")).addChild(new Dog("Zetta")); // method addChild return self object
 
//named args. hour arg in method have default value
dog.goToSleep(minutes=3, wakeUpCallback=(string message) {
  IO.Console.writeLine(message);  // closure
}); 

Nullable<Dog> child = dog.getFirstChild();

if (child.isNotNull()) {
  IO.Console.writeLine(child.object().getName()); 
}

annotation logCall(Function callingFunction, FunctionArgs args, file) {
 IO.File.open(file).writeLine('Call function ${callFunction.name} with args ${functionArgs} ');
 callFunction(args);
}

@logCall(file="functionCalls.log")
IO.Console.writeLine("hello"); 
```

**Comment by zegl** [comment]
Hi, thanks for the feedback!

I've adressed the ones that I have something to say about one by one.

* Instead class, make interface and implementations. 
* Make static typed language with reference counting garbage collector.

Currently one of the goals of Gus is to create a simple scripting language. 

* All methods returns self object by default if not return anything.

Seems like a great idea! I've added it as a separate issue. #41

* Make named arguments.

I totally agree! See #40

* Make annotations (see python annotations).

I have no experience with annotations in Python. I'll investigate if it fits the language and it's purpose.

* Make primitive types with unsigned analogs: string (unicode string), (u)byte, (u)short, (u)int, (u)int64, (u)float, (u)float64, null.

For now, I think that the available primitive types (String, Number, Bool, Null) is enough. I like to keep it simple.

* Do not make exceptions for error.

I have yet to figure out how to handle error reporting from within Gus. Both Go-way (an error type, used with multiple return values) and the Java-way (exceptions) will be used for inspiration when that day comes.
